GpuFreq=control_disabled
Loading checkpoint shards:   0%|          | 0/11 [00:00<?, ?it/s]Loading checkpoint shards:   9%|▉         | 1/11 [00:05<00:51,  5.15s/it]Loading checkpoint shards:  18%|█▊        | 2/11 [00:11<00:51,  5.75s/it]Loading checkpoint shards:  27%|██▋       | 3/11 [00:17<00:48,  6.09s/it]Loading checkpoint shards:  36%|███▋      | 4/11 [00:24<00:43,  6.25s/it]Loading checkpoint shards:  45%|████▌     | 5/11 [00:30<00:38,  6.34s/it]Loading checkpoint shards:  55%|█████▍    | 6/11 [00:36<00:29,  5.96s/it]Loading checkpoint shards:  64%|██████▎   | 7/11 [00:38<00:19,  4.83s/it]Loading checkpoint shards:  73%|███████▎  | 8/11 [00:40<00:12,  4.03s/it]Loading checkpoint shards:  82%|████████▏ | 9/11 [00:43<00:07,  3.53s/it]Loading checkpoint shards:  91%|█████████ | 10/11 [00:45<00:03,  3.19s/it]Loading checkpoint shards: 100%|██████████| 11/11 [00:47<00:00,  2.69s/it]Loading checkpoint shards: 100%|██████████| 11/11 [00:47<00:00,  4.30s/it]
Traceback (most recent call last):
  File "/home/hgf_hmgu/hgf_tfv0045/meta-learning-synthetic-data/src/synth_data_prompt.py", line 91, in <module>
    df = pd.DataFrame(synthetic_data)
  File "/hkfs/home/haicore/hgf_hmgu/hgf_tfv0045/meta-learning-synthetic-data/env/lib64/python3.9/site-packages/pandas/core/frame.py", line 875, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
srun: error: haicn1709: task 0: Exited with exit code 1
